version: '3.7'
services:
    server:
        build:
            context: .
            target: server
        ports:
            - "8088:8088"
        command: >
            /bin/sh -c "
                cargo build --release &&
                cargo run --release
            "
        networks:
            - default
            - shared-network


    client: 
        build:
            context: .
            target: client
        depends_on:
            - server
        command: >
            /bin/sh -c "
                wait-for-it -t 0 server:8088 &&
                cargo test --test e2e_test
            "
        networks:
            - default
            - shared-network


networks:
  shared-network:
    external: true