version: '3.7'
services:
    webapi:
        build:
            context: .
            target: webapi
        ports:
            - "8088:8088"
        command: ["cargo", "build", "--release", "--", "cargo", "run", "--release"]
        

    client: 
        build:
            context: .
            target: client
        depends_on:
            - webapi
        command: ["wait-for-it", "-t", "0" "webapi:8088", "--", "cargo", "test", "--test", "e2e_test"]